# Generated by Django 4.1.1 on 2022-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDependencies',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('start_commit', models.DateField()),
                ('last_commit', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(to='app.projectdependencies')),
            ],
        ),
    ]
