# Generated by Django 4.1.1 on 2022-10-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='ProjectDependencies',
            new_name='ProjectDependency',
        ),
    ]
