# Generated by Django 4.1.3 on 2022-11-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_projects_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="dependencies",
        ),
        migrations.RemoveField(
            model_name="project",
            name="finished",
        ),
        migrations.AddField(
            model_name="project",
            name="content_as_markdown",
            field=models.TextField(default="", editable=False),
        ),
        migrations.AddField(
            model_name="project",
            name="href",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="main_content",
            field=models.TextField(
                default="full description with **[markdown](https://commonmark.org)**"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="ProjectDependency",
        ),
    ]
