# Generated by Django 4.1.3 on 2022-11-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_project_dependencies_remove_project_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_as_markdown',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_content',
        ),
    ]
