# Generated by Django 4.1.3 on 2022-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_content_as_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='href',
            field=models.CharField(max_length=20),
        ),
    ]
