# Generated by Django 4.1.3 on 2022-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='href',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
