# Generated by Django 4.1.3 on 2022-11-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(null=True),
        ),
    ]
