# Generated by Django 4.1.3 on 2022-11-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_git_url_project_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
